In [33]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

In [34]:
W = pd.read_csv("./SmallDataSet/sim0.csv")
print(W.head(4))

          y        X1        X2        X3
0  0.845427  0.185279 -1.236787  0.326003
1  0.433077  0.997556  0.087373  0.640670
2  0.263135 -0.147238  0.166109  1.428932
3  1.000000 -2.612769  1.439875 -0.323949


In [45]:
x = np.hstack((np.ones((W.shape[0], 1)), np.array(W.iloc[:, 1:])))
y = np.array(W.y).reshape(-1, 1)
print(x)
print(y)

[[ 1.          0.18527887 -1.23678724  0.3260035 ]
 [ 1.          0.9975558   0.08737292  0.64066954]
 [ 1.         -0.14723765  0.16610889  1.42893194]
 [ 1.         -2.61276867  1.43987499 -0.32394923]
 [ 1.         -1.6436483   0.75490919 -0.70877946]
 [ 1.          0.04660723  0.49063147  1.45423253]
 [ 1.         -2.22695471 -0.81180776 -0.87758789]
 [ 1.         -0.5650898  -1.3641352   0.61435879]
 [ 1.         -2.46071717  0.66283758 -0.94648412]
 [ 1.          2.17705998  0.8415159   0.43838626]
 [ 1.         -0.15930549  0.2306561  -0.80982733]
 [ 1.         -2.02498597 -2.34736297 -0.08846107]
 [ 1.          0.34678655 -0.13950418 -0.87267463]
 [ 1.         -0.71836143 -0.54262954  0.80629708]
 [ 1.         -1.92384557  0.25694697  0.19029125]
 [ 1.          1.44180534  0.532667   -0.59848279]
 [ 1.          0.2690708  -0.37023831  0.36019862]
 [ 1.          1.60612187 -0.51877893 -0.06670851]
 [ 1.          0.1225853   1.41020895 -0.21129074]
 [ 1.         -0.82198937 -0.31